Added Syncromatics DX templates
syncromatics/Syncromatics.Clients.Marta pull request #2
Opened 2018-10-03 20:25 UTC by kproth

I updated the template for the MARTA project by updating the buttons that point to the client that supports the MARTA API.  Also edited the readme and code of conduct files.

2018-10-03 20:36 UTC, kennethito approved these changes

2018-10-03 20:39 UTC, thzinc requested changes

2018-10-03 20:39 UTC, thzinc commented on README.md
> +Write a single-paragraph explanation of this project. It should describe what the software does and why it exists. Finish the paragraph with a compelling reason to use the software.
@kproth, would you mind changing this to `This is a .NET library to interact with the MARTA API for getting transit arrival information in Atlanta`

2018-10-12 20:06 UTC, thzinc approved these changes

2018-10-12 20:47 UTC, thzinc requested changes
This looks good, with one minor addition. Thanks for adding this documentation!

2018-10-12 20:47 UTC, thzinc commented on README.md
> +
This project has some very basic steps for building. Would you mind adding the following under the badges in this section?

    This library is built using [.NET Core](https://www.microsoft.com/net/download). To build:

    ```
    dotnet build
    ```

    To run the tests:

    ```
    dotnet test
    ```

2019-01-25 17:50 UTC, thzinc approved these changes

2019-01-25 17:51 UTC, merged